dos2unix public_arch_0_job_dual_bayesian_univariate.sh
sh public_arch_0_job_dual_bayesian_univariate.sh
dos2unix movielens_arch_0_job_dual_bayesian_univariate.sh
sh movielens_arch_0_job_dual_bayesian_univariate.sh


