dos2unix public_arch_0_job_dual_bayesian_univariate.sh
sh public_arch_0_job_dual_bayesian_univariate.sh
dos2unix public_arch_0_job_dual_bayesian_multivariate.sh
sh public_arch_0_job_dual_bayesian_multivariate.sh